// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dkusaynnwwcebpmwfqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRrdXNheW5ud3djZWJwbXdmcWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDgyMTAsImV4cCI6MjA3NDQyNDIxMH0.y2Yuk99514T1WBQRsLiT56-BhUAgDf7Y4rzSe42QLG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);